spring:
    application:
        name: portal
server:
    port: 443
    ssl:
      key-store: classpath:keystore.p12
      key-store-password: amaramar
      keyStoreType: PKCS12
      keyAlias: tomcat